# E-Commerce Sales & Customer Revenue Analytics

## Project Overview

This project analyzes historical e-commerce transaction data to understand sales performance, customer purchasing behavior, product demand, and revenue trends.

The analysis uses Python and Pandas for data preparation and exploratory data analysis, followed by SQL-based business analysis and an interactive Power BI dashboard.

## Business Problem

E-commerce businesses need to understand their sales performance, customer purchasing behavior, and product demand in order to make informed decisions about revenue growth, customer retention, and product strategy.

This project uses historical transaction-level e-commerce data to identify sales trends, high-value customers, top-performing products, purchasing patterns, and other factors that influence overall revenue.

## Project Objectives

* Analyze overall sales and revenue performance.
* Identify monthly and yearly revenue trends.
* Identify the countries generating the highest revenue.
* Identify the top-performing products by sales and quantity.
* Analyze customer purchasing behavior and identify high-value customers.
* Analyze repeat purchasing patterns.
* Examine cancelled and returned transactions and their impact on sales.
* Generate actionable business recommendations based on the analysis.

## Tools & Technologies

* **Python** — Data analysis and preprocessing
* **Pandas** — Data manipulation and cleaning
* **Matplotlib** — Data visualization
* **Seaborn** — Exploratory data visualization
* **SQL** — Business-oriented data analysis
* **Power BI** — Interactive dashboard and reporting

## Dataset

The dataset contains historical transaction-level records from an online retail business. It covers transactions from two periods: 2009–2010 and 2010–2011.

The two sheets contain the same set of variables and will be combined into a single dataset before performing further analysis.

### Key Variables

| Column      | Description                           |
| ----------- | ------------------------------------- |
| Invoice     | Unique invoice/transaction identifier |
| StockCode   | Product or item identifier            |
| Description | Product description                   |
| Quantity    | Number of units purchased             |
| InvoiceDate | Date and time of the transaction      |
| Price       | Unit price of the product             |
| Customer ID | Customer identifier                   |
| Country     | Customer's country                    |

The combined dataset contains more than one million transaction records, providing sufficient data for analyzing sales, customer behavior, and product performance.

# 1. Data Loading & Initial Inspection

### Import Required Libraries

The following Python libraries will be used for data loading, manipulation, numerical analysis, and visualization.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Display all columns when working with the dataset
pd.set_option('display.max_columns', None)

### Load the Dataset

The dataset is stored in an Excel workbook containing two sheets representing transaction data for different periods.

Both sheets will be loaded separately first so that their structure, columns, and data types can be validated before combining them.

In [3]:
file_path = "../data/raw/online_retail_II.xlsx"

df_2009_2010 = pd.read_excel(
    file_path,
    sheet_name="Year 2009-2010"
)

df_2010_2011 = pd.read_excel(
    file_path,
    sheet_name="Year 2010-2011"
)

### Check Dataset Dimensions

Before combining the two datasets, we check the number of rows and columns in each sheet.

In [4]:
print("2009-2010:", df_2009_2010.shape)
print("2010-2011:", df_2010_2011.shape)

2009-2010: (525461, 8)
2010-2011: (541910, 8)

In [5]:
print("2009-2010 columns:")
print(df_2009_2010.columns.tolist())

print("\n2010-2011 columns:")
print(df_2010_2011.columns.tolist())

2009-2010 columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

2010-2011 columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

### Check Data Types

Before combining the datasets, the data types of each column are checked to ensure that both sheets have compatible structures and that important fields such as dates, quantities, and prices are represented correctly.

In [6]:
print("2009-2010 Data Types:")
print(df_2009_2010.dtypes)

print("\n2010-2011 Data Types:")
print(df_2010_2011.dtypes)

2009-2010 Data Types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

2010-2011 Data Types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

### Combine the Datasets

Both yearly datasets have the same columns and compatible data types. Therefore, the datasets can be combined by appending the rows into a single DataFrame.

This will create one consolidated transaction dataset covering both periods.

In [7]:
# Combine both yearly datasets
df = pd.concat(
    [df_2009_2010, df_2010_2011],
    ignore_index=True
)

In [8]:
print("Combined dataset shape:", df.shape)

Combined dataset shape: (1067371, 8)

In [9]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [10]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

### Initial Dataset Inspection

After combining the two yearly datasets, the consolidated DataFrame is inspected to understand its structure, sample records, column names, and data types before performing any data cleaning.

In [11]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [12]:
df.shape

(1067371, 8)

In [13]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [14]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB